### ISSUE TITLE
cargo-0.4.0 doesn't compile with rust-1.2.0

### ISSUE THREAD

**Issue by Dr-Terrible** [gentoo/gentoo-rust#13]
When compiling `cargo` v0.4.0 with `rust` v1.2.0 I got the following error:

```
error: "ar" "crs" "/var/tmp/portage/dev-util/cargo-0.4.0/work/cargo-0.4.0/target/x86_64-unknown-linux-gnu/release/deps/libmatches-177d469cebea8d6e.rlib" "matches-177d469cebea8d6e.o" "rust.metadata.bin" "matches-177d469cebea8d6e.0.bytecode.deflate" failed with: signal: 11
note: stdout ---

note: stderr ---

error: aborting due to previous error
```

It seems there is a problem with dependency `matches` v0.1.2.

The issue disappears when I compile cargo with `rust-1.1.0` or `rust-bin-1.1.0` (both of them are already gone from this overlay, but I still have them installed from the previous overlay). My guess is that `matches` v0.1.2 is not compatible with `rust` v1.2.x, and some tweak is necessary to make it compile with new versions of rust.

**Comment by gentoo90** [comment]
I've just built `cargo-0.4.0` successfully with both `rust-1.2.0` (`system-llvm` enabled and `llvm-3.6.0` ) and `rust-bin-1.2.0`.
Did you try `rust-bin-1.2.0`? Which useflags are enabled for `rust`?

**Comment by Dr-Terrible** [comment]
> Did you try rust-bin-1.2.0? 

Yup, same result.

> Which useflags are enabled for rust?

From a clean Gentoo installation without llvm/clang and rust:

```
These are the packages that would be merged, in order:

[ebuild  N   ~] sys-devel/llvm-3.6.2:0/3.6::gentoo USE="clang gold libffi multitarget ncurses static-analyzer xml -debug -doc -libedit -ocaml -python {-test}" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild  N   ~] sys-devel/clang-3.6.2-r100:0/3.6::gentoo USE="multitarget static-analyzer -debug -python" 0 KiB
[ebuild  N   ~] app-eselect/eselect-rust-0.3_pre20150428::rust 0 KiB
[ebuild  N    ] net-libs/libssh2-1.5.0::gentoo USE="zlib -gcrypt -static-libs {-test}" 0 KiB
[ebuild  N   ~] dev-lang/rust-1.2.0:stable::rust USE="clang system-llvm -debug -doc -libcxx" 0 KiB
[ebuild  N   ~] dev-util/cargo-0.4.0::rust USE="-doc" 0 KiB
```
I can reproduce the issue on all the Gentoo installations in my possession, but since `cargo` (by design) doesn't redirect _stderr_ and _stdout_ during the compilation phase, there is nothing that I can report except an _exit code 101_:

```
Process didn't exit successfully: `rustc /var/tmp/portage/dev-util/cargo-0.4.0/work/matches-0.1.2/lib.rs --crate-name matches --crate-type lib -C opt-level=3 -C metadata=177d469cebea8d6e -C extra-filename=-177d469cebea8d6e --out-dir /var/tmp/portage/dev-util/cargo-0.4.0/work/cargo-0.4.0/target/x86_64-unknown-linux-gnu/release/deps --emit=dep-info,link --target x86_64-unknown-linux-gnu -L dependency=/var/tmp/portage/dev-util/cargo-0.4.0/work/cargo-0.4.0/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/var/tmp/portage/dev-util/cargo-0.4.0/work/cargo-0.4.0/target/x86_64-unknown-linux-gnu/release/deps` (exit code: 101)
```

Here my `emerge --info` (all my Gentoo installations have the same configuration): http://pastebin.com/XYwCCsKi

**Comment by jauhien** [comment]
Please, try to build `matches v0.1.2` by hand, asking cargo to be verbose and show here what output you get.

**Comment by jauhien** [comment]
As the fast fix, please, use `cargo-bin`.

**Comment by Dr-Terrible** [comment]
> Please, try to build matches v0.1.2 by hand, asking cargo to be verbose and show here what output you get.

Here the logs, from a new Gentoo installation made just for the occasion (`rust-1.2.0::rust` + `cargo-bin-999::rust`): http://pastebin.com/vSqk7GBT

My guess was correct, `[feature(step_by)]` is an _unstable_ feature therefore isn't enabled on stable release of `rustc`; it was enable by mistake in `rust-1.1.0`, and then removed again for the subsequent versions. That is why I'm able to compile `cargo-0.4.0` with the old `rust{-bin}-1.1.0` ebuilds. See here for a reference: https://github.com/rust-lang/rust/issues/25499

> As the fast fix, please, use cargo-bin.

Yup, at the moment it's the only version of cargo that is installable from the overlay.
For now, it's fine for my needs.

**Comment by jauhien** [comment]
@Dr-Terrible: I haven't look at source cargo package so far. It can be that it is uncompilable with stable compiler by design, then I suggest using unstable rust. If this is true, I'll fix cargo deps. But I'll manage to look at source cargo only in the nearest weeks, not days.

**Comment by Dr-Terrible** [comment]
Here, I have forked `matches`'s repository and fixed `.travis.yml` to properly build / test the crate against `rust-1.0.0`, `rust-1.1.0`, `rust-1.2.0`, `rust-beta`, and `rust-nightly`: https://travis-ci.org/Dr-Terrible/rust-std-candidates/builds/80205882

As you can see, only `rust-nightly` compiles `matches`.

@gentoo90's argument begs the question. How were you able to compile `cargo-0.4.0` with `rust-{bin}1.2.0` in the first place? Formal logic suggests that your Gentoo testing set-up is somehow screwed up. Most probably your $PATH is polluted by a _nightly_ release of rustc.

> But I'll manage to look at source cargo only in the nearest weeks, not days.

Don't worry about that. I have found a simple workaround to make cargo-0.4.0 compile and so far it seems to run fine. I'll open a PR with the proper fix in the next few hours (together with some extra enhancements for the cargo ebuild).
