### ISSUE TITLE
Old GitHub issues gone missing

### ISSUE THREAD

**Issue by wthrowe** [gentoo/gentoo-rust#162]
It seems that something was changed with this repo that replaced the contents of the issue tracker with a different set of issues.  This is rather confusing (it broke all the crossreferences), but more importantly there were actual bugs in the old list that have now vanished without a trace.  Is there any chance they can be recovered somehow?

**Comment by Heather** [comment]
@wthrowe yes, they are here: https://github.com/Heather/gentoo-rust/issues

I've switched repositories so this became the main one (to not confuse people)
It will be good to port missing actual issue back to here and disable issues inside fork
