### ISSUE TITLE
dev-lang/rust-9999 always fails to compile anything: "can't find crate for `std` [E0463]" 

### ISSUE THREAD

**Issue by mceier** [gentoo/gentoo-rust#163]
dev-lang/rust-9999 can't compile even the most trivial programs:

```rust
fn main() {}
```
it always shows following error:

> main.rs:1:1: 1:1 error: can't find crate for `std` [E0463]

**Comment by mceier** [comment]
It's also reproducible with dev-lang/rust-999. Now I'm emerging dev-lang/rust:beta. I'm not sure if it's ebuild issue or rust issue.

**Comment by mceier** [comment]
In dev-lang/rust:beta there's no issue - so probably breaking change was introduced in rust build system.

**Comment by mceier** [comment]
Nightly rustc tries to open '/usr/lib64/rust-999/rustlib/x86_64-unknown-linux-gnu/lib' which doesn't exist; instead  rustlib is located in /usr/lib/rustlib.

I reverted https://github.com/rust-lang/rust/commit/ea798b9e25600182d623604ea7952f90d23b2d0f commit which was suggested by @bluss and it fixed this issue.

/cc @wthrowe

**Comment by wthrowe** [comment]
The ebuilds are currently applying an old patch that conflicts with that commit (the old install path problem is being corrected twice leading to an error in the other direction).  I filed #159 for the removal of the patch, but it hasn't been done yet.

I'll try to submit a pull request for that later today.

**Comment by mceier** [comment]
Ok, thanks :)
