### ISSUE TITLE
[dev-lang/rust-1.5.0] recipe for target stamp.rustc failed

### ISSUE THREAD

**Issue by Dr-Terrible** [gentoo/gentoo-rust#168]
When building `dev-lang/rust-1.5.0::rust` I got this compilation issue:

> x86_64-unknown-linux-gnu/stage2/lib64/rust-1.5.0/rustlib/x86_64-unknown-linux-gnu/lib/librustc_back-gentoo-stable.rlib
/var/tmp/portage/dev-lang/rust-1.5.0/work/rustc-1.5.0/mk/target.mk:164: recipe for target 'x86_64-unknown-linux-gnu/stage2/lib64/rust-1.5.0/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc' failed
make: *** [x86_64-unknown-linux-gnu/stage2/lib64/rust-1.5.0/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc] Killed
 * ERROR: dev-lang/rust-1.5.0::rust failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/rust-1.5.0::rust'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/rust-1.5.0::rust'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/rust-1.5.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/rust-1.5.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-lang/rust-1.5.0/work/rustc-1.5.0'
 * S: '/var/tmp/portage/dev-lang/rust-1.5.0/work/rustc-1.5.0'

`dev-lang/rust-1.5.0::rust` is built with the following USE flags: `USE="doc -clang -debug -libcxx -system-llvm%""`.

I'm using `sys-devel/clang-3.7.0-r100::gentoo` and `sys-devel/llvm-3.7.0-r2::gentoo`.

**Comment by Dr-Terrible** [comment]
This issue is not happening with `dev-lang/rust-1.6.0::rust`. The package compiles file, and so far, rust seems to work correctly.

**Comment by Heather** [comment]
@Dr-Terrible just recently pulled correction for 1.6.0

**Comment by Dr-Terrible** [comment]
Thank for the heap up; I'll test fd0153e too.
