### ISSUE TITLE
Rust 1.3 release

### ISSUE THREAD

**Issue by jauhien** [gentoo/gentoo-rust#17]
http://blog.rust-lang.org/2015/09/17/Rust-1.3.html

Working on version bump, should be done this weekend.

**Comment by jauhien** [comment]
I have problems with system-llvm now, as llvm is not installed with static libs now. And rust needs static ones (and I do not want to change rust build system and look for resulting bugs). I'll ask in IRC and may be dev-list. If this will not help, I'll mask system-llvm for a while and make version bump without it.

**Comment by jauhien** [comment]
There's no good possibility to build LLVM static libs on Gentoo now. So rust should use shared ones, I will remove system-llvm USE for a while and try to discuss this topic with Rust upstream.

Btw, for those interested: topic about rust packaging: https://internals.rust-lang.org/t/perfecting-rust-packaging/2623

**Comment by lvii** [comment]
@jauhien rust configure option `--llvm-root=/usr` means compiling rust with LLVM **static libs** ?

I find that llvm package has not `static` USE, and LLVM ebuild config with  `--enable-shared` option or `-DBUILD_SHARED_LIBS=ON`:

```
/usr/portage/sys-devel/llvm/llvm-3.5.0.ebuild

    multilib_src_configure() {
        # disable timestamps since they confuse ccache
        local conf_flags=(
            --disable-timestamps
            --enable-keep-symbols
            --enable-shared
            ...

/usr/portage/sys-devel/llvm/llvm-3.7.0.ebuild

    local mycmakeargs=(
        "${mycmakeargs[@]}"
        -DLLVM_LIBDIR_SUFFIX=${libdir#lib}

        -DBUILD_SHARED_LIBS=ON
        ...
```

Does gentoo's LLVM installed as **dylibs** make rust compiling failed ?

https://github.com/rust-lang/rust/pull/27937

> Yes, it looks like it uses CMake with `-DBUILD_SHARED_LIBS=ON`. (This is Gentoo's official llvm-3.7.0 package.)

https://internals.rust-lang.org/t/perfecting-rust-packaging/2623/16

> > I'll try to give a fuller reply later, but one thing I don't see mentioned at all here is ABI. **Fedora usually avoids static linking in packages**, but I don't see how we can ship any dylibs if there's no way to update them. Even just std is questionable, it seems.
> 
> Yes, this is the case. Using **dylibs** for the most common thing dylibs are used for (providing ABI-compatible updates) is **NOT viable in Rust right now**. **Static linking is strongly preferred** by the entire system atm. Solving this is far-future territory :frowning:
> 
> Since Rust **much prefers** static linking, will Fedora use it, or will Fedora want to dylib crates anyway?
> 
> We may be able to make some quick fixes here **on native dylibs**. I suspect that a lot of crates are 'vendoring' their native libs and not providing an option to dynamically link them.

thx.

**Comment by jauhien** [comment]
@lvii: thanks for the link to PR. Rust has the same problem at least on BSD as far as I know, so I hope upstream will fix it finally. I'll release 1.3.0 with bundled libraries after I'll test it.

Also I have problems with unbundling jemalloc.

**Comment by lvii** [comment]
@jauhien I have tested installing rust 1.3 by customing ebuild from portage: 

https://github.com/lvii/outman/blob/master/dev-lang/rust/rust-1.3.0.ebuild

Did Rust compile **statically** with its **bundled** llvm under `rustc-${P}/src/llvm` dir by disable `llvm` USE ?

If rust compiled with its bundled llvm statically, could rust ebuild not depend on system-wide llvm (ebuild could remove llvm dependency) ?

Thx.

**Comment by jauhien** [comment]
@lvii, please, read ebuild carefully. It depends on llvm only when system-llm USE is set. What is your question about?

**Comment by jauhien** [comment]
Pushed to the tree. For system LLVM support see issue #21.
