### ISSUE TITLE
Broken std crate in installation of rust-1.6.0

### ISSUE THREAD

**Issue by bruceg** [gentoo/gentoo-rust#170]
After installing dev-lang/rust-1.6.0, all builds using rust fail with:

src/lib.rs:1:1: 1:1 error: can't find crate for `std` [E0463]
src/lib.rs:1 //! Support for concurrent and parallel programming.

The relevant USE flags from emerge -v are:

USE="clang -debug -doc -libcxx -system-llvm%"

**Comment by Heather** [comment]
@bruceg I wonder if that is related stage0, can't find correct link for them

here

https://github.com/gentoo/gentoo-rust/blob/master/dev-lang/rust/rust-1.6.0.ebuild#L17-L18

**Comment by bruceg** [comment]
I don't think so. I checked the source tarball, and the latest snapshots listed in src/snapshots.txt match what is in the ebuild:

S 2015-08-11 1af31d4
  linux-i386 e2553bf399cd134a08ef3511a0a6ab0d7a667216
  linux-x86_64 7df8ba9dec63ec77b857066109d4b6250f3d222f

**Comment by Heather** [comment]
is it related https://github.com/rust-lang/rust/issues/29418

**Comment by Heather** [comment]
all info I've found is that std is on separated package, guess we need include it somehow there if it's really so

**Comment by bruceg** [comment]
Undoubtedly, it's related to that rust change, but the sources for the std crate are still part of rustc-1.6.0-src.tar.gz. So, it'll be a difference in the build or install process (or default locations).

**Comment by bruceg** [comment]
In terms of the install image, the difference is that the ebuild is now installing the .rlib files into /usr/lib/rustlib/x86_64-unknown-linux-gnu/ where they previously were installed into /usr/lib64/rust-1.5.0/rustlib/x86_64-unknown-linux-gnu/.

Also, some of the .so files are being installed into base /usr/lib instead of /usr/lib64/rust-1.5.0.

Doing a strace on the rustc 1.6.0 binary, it is failing trying to open /usr/lib64/rust-1.6.0/rustlib/x86_64-unknown-linux-gnu/lib. So the difference in the install paths seems to be the difference.

**Comment by Heather** [comment]
do you suggest to add some mv's to https://github.com/gentoo/gentoo-rust/blob/master/dev-lang/rust/rust-1.6.0.ebuild#L82 ?

**Comment by negge** [comment]
I was seeing this problem when installing dev-util/cargo-0.8.0.ebuild.  I was able to get around it by installing dev-lang/rust-bin-1.6.0 and using eselect to switch to rust-bin.  Would be nice to have a working dev-lang/rust-1.6.0 though.

**Comment by wthrowe** [comment]
I think I have a fix.  I'll submit a pull request tomorrow after my computer finishes recompiling to verify it.

**Comment by negge** [comment]
Thanks Heather, I just installed dev-lang/rust-1.6.0-r1 and it seems to be working now.

**Comment by bruceg** [comment]
Yes, thanks. Works for me too.
