### ISSUE TITLE
dev-lang/rust-1.7.0-r100 linker error with system-llvm 3.7.1-r1

### ISSUE THREAD

**Issue by jfkw** [gentoo/gentoo-rust#181]
When emerging dev-lang/rust-1.7.0-r100::rust and USE=system-llvm where system is ~x64 and installed llvm is sys-devel/llvm-3.7.1-r1, a linker error results:

```
note: /var/tmp/portage/dev-lang/rust-1.7.0-r100/work/rustc-1.7.0/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-6a154fe0.so: undefined reference to `llvm::Triple::normalize(llvm::StringRef)'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
/var/tmp/portage/dev-lang/rust-1.7.0-r100/work/rustc-1.7.0/mk/target.mk:202: recipe for target 'x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc' failed
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc] Error 101
 * ERROR: dev-lang/rust-1.7.0-r100::gentoo failed (compile phase):
```

IIUC, rust would prefer llvm-3.6.x, and the initial rust-1.7.0 ebuild did enforce that. The -r100 version seems to have relaxed the check. No expectation that I'd be able to use an unsupported newer llvm if that is the case,  this is just a report that the check might be failing intended purpose.

emerge --info attached:
[emerge-info.txt](https://github.com/gentoo/gentoo-rust/files/213526/emerge-info.txt)

Sidebar: what does the -r100 designation signify?

**Comment by Heather** [comment]
hm.... @jfkw thanks for that first

actually we need to dig into PR history

because I think someone has success with llvm 3.7 and that's why it was unmasked there by his PR

**Comment by Heather** [comment]
@jfkw waita wait... check this out https://github.com/gentoo/gentoo-rust/tree/master/dev-lang/rust
where is this mystic `r100`

**Comment by jfkw** [comment]
You're correct, I overlooked that r100 lives in ::gentoo, not ::rust:

[ebuild     U  ] dev-lang/rust-1.7.0-r100:stable/1.7::gentoo [1.7.0:stable/stable::rust] USE="clang system-llvm* -debug -doc -libcxx" 0 KiB

I can file a bug with gentoo. I still wonder why the r100 designation.

**Comment by Heather** [comment]
@jfkw git blame is very useful there https://github.com/gentoo/gentoo/blame/master/dev-lang/rust/rust-1.7.0-r100.ebuild#L50 /cc @cardoe 

ideally we also need to sync work in `::gentoo` with this overlay

**Comment by Heather** [comment]
seems like `r100` is exactly llvm support bump https://github.com/gentoo/gentoo/commit/dbc7ce142d85a62851ae1cf14daf003ed3fb4baf

**Comment by cardoe** [comment]
-r100 is to add the RDEPEND on LLVM 3.7.1-r1 and newer. -r0 in tree and -r1 in the overlay has a DEPEND on LLVM 3.6.0 and older. The EAPI spec doesn't allow us to dynamically adjust RDEPEND based on what the package is built against.

**Comment by Heather** [comment]
@cardoe seems like it doesn't work with llvm 3.7.1-r1, as from issue text

**Comment by cardoe** [comment]
@Heather That's how I've been using it on all my machines.

```
$ equery list llvm rust
 * Searching for llvm ...
[IP-] [  ] sys-devel/llvm-3.7.1-r1:0/3.7.1

 * Searching for rust ...
[IP-] [  ] dev-lang/rust-1.7.0-r100:stable/1.7
$ emerge -pv llvm rust

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] sys-devel/llvm-3.7.1-r1:0/3.7.1::gentoo  USE="libffi multitarget ncurses static-analyzer -clang -debug -doc -gold -libedit -lldb -ocaml -python {-test} -xml" ABI_X86="(64) -32 (-x32)" PYTHON_TARGETS="python2_7" VIDEO_CARDS="radeon" 0 KiB
[ebuild   R   ~] dev-lang/rust-1.7.0-r100:stable/1.7::gentoo  USE="system-llvm -clang -debug -doc -libcxx" 0 KiB
```

I mentioned to @jfkw on the Gentoo bug that the initial difference seems between our setups is USE=clang. But I can't see the USE flags that he built LLVM with so its impossible to know if there are other changes there.

**Comment by jfkw** [comment]
Information as posted to the Gentoo bug:

llvm and clang USE vars on affected system:
```
[ebuild   R    ] sys-devel/llvm-3.7.1-r1:0/3.7.1::gentoo  USE="clang libffi multitarget ncurses python static-analyzer xml -debug -doc -gold -libedit -lldb -ocaml {-test}" ABI_X86="(64) -32 (-x32)" PYTHON_TARGETS="python2_7" VIDEO_CARDS="-radeon" 0 KiB
[ebuild   R    ] sys-devel/clang-3.7.1-r100:0/3.7::gentoo  USE="python static-analyzer -debug -multitarget" ABI_X86="(64) -32 (-x32)" 0 KiB
```

**Comment by cardoe** [comment]
@williamh Any chance you've got some speedy hardware that can build this with USE=clang?

**Comment by cardoe** [comment]
This should be fixed with newer versions.
