### ISSUE TITLE
dev-rust/cargo should have libressl USE flag.

### ISSUE THREAD

**Issue by strelec** [gentoo/gentoo-rust#188]
Gento is progressively moving towards all packages supporting the alternative SSL librarly, named libressl. We should have an option to use it.

An alternative is to remove the openssl dependecy altogether. The SSL support comes from CURL already, which is built with +ssl.

**Comment by cardoe** [comment]
That would involve creating a libressl wrapper crate and making things optionally depend on that. This isn't something we can fix downstream.

**Comment by Esption** [comment]
@cardoe What exactly needs a wrapper downstream? I just built cargo-9999 by making a quick patch to the ebuild for it to support the libressl use flag and it compiled perfectly fine.  My guess is this is the same for previous cargo versions too.

	!libressl? ( dev-libs/openssl:* )
	libressl? ( dev-libs/libressl:0 )

**Comment by strelec** [comment]
@Esption Thanks, this works for me.

**Comment by stratact** [comment]
How hard would it be to integrate @Esption's changes to the cargo ebuilds? I need this to be included, because I made my switch to using libressl and I can't install cargo because of the hard openssl dependency since openssl conflicts with libressl.

**Comment by Esption** [comment]
@stratact Not very... I can submit a PR, but I'm not sure if this is the main repo or not.

**Comment by Wonko7** [comment]
I was going to patch the ebuild, but if you guys have done it, could you ask for a pull request on the official portage tree?
