### ISSUE TITLE
remove dev-lang/rust and dev-util/cargo from overlay

### ISSUE THREAD

**Issue by cardoe** [gentoo/gentoo-rust#191]
Rather than duplicating ebuilds let's keep the official ebuilds in tree and if the overlay wants to have different versions it can have those.

**Comment by Cynede** [comment]
@cardoe agreed in general
but we should keep 99(what is it even)/999/9999 versions here
also, what about `rust-bin` and `eselect-rust`

**Comment by cardoe** [comment]
We should remove eselect-rust from the overlay as well. It has not had a version change in years and its committed to the tree. We can remove rust-bin as well but I'm less good at keeping that up to date in the tree.

**Comment by Cynede** [comment]
rust-1.6.0-r1.ebuild and 1.4.0 either should be removed, because it should not look like that is last versions
