### ISSUE TITLE
Create a proper eclass for crates

### ISSUE THREAD

**Issue by suhr** [gentoo/gentoo-rust#195]
Prototype: https://github.com/suhr/badumz/blob/master/eclass/cargo-utils.eclass
Also relevant: https://github.com/gentoo/gentoo/blob/master/eclass/cargo.eclass

Unresolved questions:
- Should we download sources somewhere to `distfiles`
- How to combine `cargo fetch` with other unpacks (git, archives)

cast @cardoe

**Comment by cardoe** [comment]
I'm working towards this. I'm actually tackling this on Yocto first. You can see an example recipe here: https://github.com/starlab-io/meta-rust/commit/112d40a37c64178a9f6378620d9e625287805a17 And you can see the rest of the commits here: https://github.com/starlab-io/meta-rust/commits/crate-fetch

Its not totally done yet. But the main tree eclass does fetch crates to `distfiles` as name-version.crate

**Comment by cardoe** [comment]
Oh and we can't use `cargo fetch` until Gentoo adds a `src_fetch` phase.

**Comment by cardoe** [comment]
What files does `cargo install` create? Does it generate additional metadata?

**Comment by suhr** [comment]
Great!

There's some problem though. Looks like it lists all dependencies in `SRC_URI`. But a list of all dependencies can be [quite](https://raw.githubusercontent.com/PistonDevelopers/piston_window/master/Cargo.png) [big](https://dirkjan.ochtman.nl/files/servo-graph.svg), so ebuilds become hard to create and edit. 

> Does it generate additional metadata?

Yep, it creates `$CARGO_HOME/.crates.toml`. We don't need it because removing doesn't require cargo.

**Comment by cardoe** [comment]
I don't disagree that the dependencies become quite big. But the only way to get things in tree is that we need to let the package manager download the files until `src_fetch()` gets added in an EAPI.

I don't think ebuilds that build cargo packages should be made by hand. They should be made by a tool. see https://github.com/cardoe/cargo-ebuild that I'm working on to generate ebuilds.

You can see an example ebuild for rustfmt here: https://github.com/cardoe/gentoo/tree/rustfmt

**Comment by gentoo90** [comment]
Maybe local registries from rust-lang/cargo#2361 could be useful here

**Comment by cardoe** [comment]
@gentoo90 We're working on this in rust-lang/cargo#2857

**Comment by cardoe** [comment]
Now that we have the necessary versions in the tree, I took a swag at doing this. Please checkout https://github.com/cardoe/gentoo/tree/rustfmt

**Comment by cardoe** [comment]
Pretty sure I broke the build of cargo with this change so I'll have to work on it some more.

**Comment by cardoe** [comment]
Well `rustfmt` installs properly now. Now to sync up the ebuild with what I'm generating with https://github.com/cardoe/cargo-ebuild

**Comment by cardoe** [comment]
cargo-ebuild 0.1.2 should produce ebuilds for things published on crates.io that work with these changes.

**Comment by cardoe** [comment]
Alright. I believe everything is updated. @gentoo90 if you want to take a peek and tell me what you think of my branch? I didn't notice you had done the work already until this morning and could have probably saved myself some time using your changes.

**Comment by gibix** [comment]
this can be closed
