### ISSUE TITLE
Installation rust-9999 broken.

### ISSUE THREAD

**Issue by o01eg** [gentoo/gentoo-rust#224]
Upstream drops `/src/etc/get-stage0.py` here https://github.com/rust-lang/rust/commit/ffd3070cc9ea6d845865f11d70c220da40720d7e which was user by `src_unpack` step.

**Comment by mpkh** [comment]
try that https://github.com/gentoo/gentoo-rust/pull/225

**Comment by o01eg** [comment]
Thanks, it was fixed.
