### ISSUE TITLE
rust-999.ebuild: could not find `cargo-vendor` in `registry ...` with version `=0.1.4`

### ISSUE THREAD

**Issue by Slabity** [gentoo/gentoo-rust#243]
I am consistently unable to build nightly rust through portage on any of my systems. A few minutes into the build process, I get the following error:

```
Dist src
running: "/var/tmp/portage/dev-lang/rust-999/work/rustc-nightly-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "--force" "--debug" "--vers" "0.1.4" "cargo-vendor"
error: could not find `cargo-vendor` in `registry https://github.com/rust-lang/crates.io-index` with version `=0.1.4`


command did not execute successfully: "/var/tmp/portage/dev-lang/rust-999/work/rustc-nightly-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "--force" "--debug" "--vers" "0.1.4" "cargo-vendor"
expected success, got: exit code: 101
```

I am using the following USE flags:

`USE="clang libcxx source system-llvm -analysis -debug -doc -sanitize"`

I am able to build rust manually from the nightly tarball with the same configure options that portage uses, but trying to build it through portage always fails.

Any ideas where I should try looking?

**Comment by mpkh** [comment]
obsolete
