### ISSUE TITLE
error: failed to load source for a dependency on `num_cpus`

### ISSUE THREAD

**Issue by tmose1106** [gentoo/gentoo-rust#251]
I'm not entirely sure what the error is here since it complains about a few different things.

Here is the [build.log](https://github.com/gentoo/gentoo-rust/files/914271/rust-9999-build.log.txt) and here is my [emerge --info output](https://github.com/gentoo/gentoo-rust/files/914272/emerge-info.txt)

If you need any more info, feel free to ask. Thank you.

**Comment by mpkh** [comment]
obsolete
