### ISSUE TITLE
RLS support

### ISSUE THREAD

**Issue by suhr** [gentoo/gentoo-rust#257]
[Rust Language Server](https://github.com/rust-lang-nursery/rls)

**Comment by gentoo90** [comment]
RLS is included into `dev-lang/rust` and `dev-lang/rust-bin`. Emerge one of them with `USE="tools"` and it will be installed. Or do you mean some other kind of support?

**Comment by suhr** [comment]
I see. I'll try it out.

**Comment by o01eg** [comment]
@suhr After #274 merged `dev-lang/rust-9999[tools]` should successfully installs `rls-9999` so you can try it.

**Comment by suhr** [comment]
It works fine, I just forgot about this issue.
