### ISSUE TITLE
Make cargo depend on virtual/rust

### ISSUE THREAD

**Issue by greydot** [gentoo/gentoo-rust#259]
At the moment cargo pulls dev-lang/rust even when dev-lang/rust-bin is installed. I suppose this should be changed.

**Comment by mpkh** [comment]
@greydot yes, it's easy to obtain, fork this repository, add cargo ebuild from main tree to cloned overlay, change it there, commit, open pull request.

**Comment by greydot** [comment]
@mpkh done #260

**Comment by mpkh** [comment]
thanks
