### ISSUE TITLE
Enable system-llvm for rust-1.18

### ISSUE THREAD

**Issue by ambasta** [gentoo/gentoo-rust#270]
As per [#37609](https://github.com/rust-lang/rust/issues/37609), llvm 4 support has been merged into rust. It would be great to try out system-llvm with rust-1.18

**Comment by mpkh** [comment]
@ambasta so far it's still being contributors driven 👍

**Comment by mpkh** [comment]
good idea will be to try stuff from here https://github.com/smaeul/portage-overlay

**Comment by ambasta** [comment]
Well, that didn't work, so I spliced the ebuild here and in smaeul to https://github.com/ambasta/ambasta/blob/master/dev-lang/rust/rust-1.18.0.ebuild

Seems to work for me, though it does download the stage0 during build

**Comment by mpkh** [comment]
@ambasta there are few things: use cargo or cargo-bin in PDEPEND add LLVM_MAX_SLOT (and maybe MIN), test if cargo builds fine with it, convert all spaces into tabs. https://github.com/ambasta/ambasta/blob/master/dev-lang/rust/rust-1.18.0.ebuild#L71 - this looks unneeded and maybe some other stage0 variables
https://github.com/ambasta/ambasta/blob/master/dev-lang/rust/rust-1.18.0.ebuild#L151 - lldb should be added there
and maybe here too: https://github.com/ambasta/ambasta/blob/master/dev-lang/rust/rust-1.18.0.ebuild#L140

**Comment by ambasta** [comment]
@mpkh I removed the tabs before cat because I wanted to avoid tabs all together..

Will incorporate all the other recommendations :)

**Comment by mpkh** [comment]
@amadio repoman (ebuild QA checker) is strongly against spaces in ebuild syntax

**Comment by ambasta** [comment]
You're right.. since my vim config automatically switches b/w tab and space mode(default space unless file has tabs), I'd assumed that I'd been using spaces all this time :(

**Comment by necrose99** [comment]
[llvm-alt-0.5.0.ebuild.txt](https://github.com/gentoo/gentoo-rust/files/1388212/llvm-alt-0.5.0.ebuild.txt)

cargo-ebuild , a number of rust add-ons for llvm in rust.. via cargo crates...

**Comment by mpkh** [comment]
obsolete
