### ISSUE TITLE
cargo.eclass in overlay not functional?

### ISSUE THREAD

**Issue by abusse** [gentoo/gentoo-rust#279]
Hi everyone,

I just tried to install `dev-vcs/pijul` from the overlay and had to realise that the ebuild does basically nothing than extracting the sources. Once I remove the  `cargo.eclass` from the overlay and use the one provided by the main portage tree, the ebuild works perfectly. I am not sure if this is a bug in the overlay or related somehow to [this](https://devmanual.gentoo.org/general-concepts/overlay/index.html#overlay-and-eclasses). Anyway, I was not able to emerge with the overlay's eclass even after `emerge --regen`.

**Comment by mpkh** [comment]
updated here https://github.com/gentoo/gentoo-rust/commit/dd177c2521438d7ddaecf0b48a9ca55ab421ecf3
