### ISSUE TITLE
File collisions when installing stable and nightly rust at the same time

### ISSUE THREAD

**Issue by MJDSys** [gentoo/gentoo-rust#287]
While attempting to upgrade my copies of rust, my nightly compiler started conflicting with my stable version (1.19.0 right now).  The exact message is:
```
 * Detected file collision(s):
 * 
 *      /usr/lib64/rustlib/rust-installer-version
 *      /usr/lib64/rustlib/manifest-rustc
 *      /usr/lib64/rustlib/install.log
 *      /usr/lib64/rustlib/uninstall.sh
 *      /usr/lib64/rustlib/components
 *      /usr/lib64/rustlib/manifest-rust-std-x86_64-unknown-linux-gnu
 *      /usr/lib64/rustlib/etc/debugger_pretty_printers_common.py
 *      /usr/lib64/rustlib/etc/gdb_load_rust_pretty_printers.py
 *      /usr/lib64/rustlib/etc/lldb_rust_formatters.py
 *      /usr/lib64/rustlib/etc/gdb_rust_pretty_printing.py
```

While attempting to fix this by getting at least the python scripts into the right libdir, I realized that the live ebuild is no longer setting a custom libdir (changed from /usr/lib64/rust-9999 to /usr/lib64).  Was it intentional to change the libdir back from rust-9999?  Would a PR fixing that be accepted?  I have the beginnings of a patch to fix up the python scripts, and I can make sure the rest of those files are fixed as appropriate as well.

If not, what would be the future plan?  Should those files be extracted out to a different ebuild that all rust ebuilds can depend on?  Or should the different slots conflict with each other?

**Comment by o01eg** [comment]
It wasn't intentional just happened when I moved from `configure` to `x.py`.

Also it looks like `1.19.0` also don't install into own separate directory.

**Comment by o01eg** [comment]
Looks like `x.py` version ignores `LDPATH` so neither stable neighter nightly version could use its own libdir.

**Comment by MJDSys** [comment]
@o01eg Can this be reopened to track this?  And what should the plan be for this issue going forward?  I can work on rust's compiler some more, see if I can fix the libdir issue.  Or should those conflicting files just be handled separately?  Or should there just be a conflict between stable/beta/nightly?

**Comment by o01eg** [comment]
I'm trying to check if rpath helps. Could you also try to build rust-1.19.0 with separate libdir and then cargo by compiled rust?

**Comment by o01eg** [comment]
No, enabling rpath doesn't help either.

**Comment by o01eg** [comment]
I've opened issue https://github.com/rust-lang/rust/issues/45345 so I hope it will be solved soon.
