### ISSUE TITLE
bump cargo to 0.22

### ISSUE THREAD

**Issue by mpkh** [gentoo/gentoo-rust#295]
current versions fails to build due error-chain crate

**Comment by free-city-of-ulm** [comment]
The error seems to be with the pre-downloaded crates. If you let cargo download and compile the dependencies the build works.

**Comment by waltercool** [comment]
Some idea how to fix or workaround this? Cargo 0.22 isn't really usable right now due error-chain crate

**Comment by waltercool** [comment]
Well, just in case might work for someone, I made a little patch to make compilation works.

https://github.com/waltercool/waltercooloverlay/blob/master/dev-util/cargo/

I basically upgraded error-chain from 0.11.0-rc.2 on ebuild to 0.11.0, and added a patch file modifying the lock file to match error-chain 0.11.0

I know, solution is ugly, but I was able to compile it without much problem.

**Comment by mpkh** [comment]
@waltercool may you Pull Request that to overlay?

**Comment by waltercool** [comment]
PR made, I hope it might help someone. Works for me at least.

**Comment by mpkh** [comment]
@waltercool thank you, it works, unmasked
