### ISSUE TITLE
rust-1.22.1 missing 0001-librustc_llvm-build-Force-link-against-libffi.patch

### ISSUE THREAD

**Issue by errin07** [gentoo/gentoo-rust#304]
From rust-1.22.1.ebuild:
src_prepare() {
        eapply "${FILESDIR}/0001-librustc_llvm-build-Force-link-against-libffi.patch"

Built is missing file:
/var/tmp/portage/dev-lang/rust-1.22.1/files/0001-librustc_llvm-build-Force-link-against-libffi.patch

**Comment by mpkh** [comment]
@perfect7gentleman seems like you forgot it
