### ISSUE TITLE
www-client/firefox-57.0.1 and sys-apps/ripgrep-0.7.1 depend on dev-util/cargo which is now blocked by dev-lang/rust-1.22.1

### ISSUE THREAD

**Issue by stefantalpalaru** [gentoo/gentoo-rust#308]
I found out about this while rebuilding @world for https://www.gentoo.org/support/news-items/2017-11-30-new-17-profiles.html

**Comment by mpkh** [comment]
@stefantalpalaru yes... I don't use either of those packages
@perfect7gentleman pull requested that update

So well... this overlay is separated from tree and not sure if our stuff will be welcomed there (/cc @cardoe ) and currently I only see few very weird solutions: 1. fork both of those packages to this overlay and (you can do it with pull request) and change cargo dep to something alike we have in forked cargo.eclass or 2. push this ebuild to tree (which will possibly bring some another headache)

**Comment by perfect7gentleman** [comment]
@stefantalpalaru , you can add all dev-util/cargo versions to package.provided.
@mpkh, i don't get what you mean.

**Comment by stefantalpalaru** [comment]
> dev-lang/rust-1.22.1 doesn't block dev-utl/cargo afaik

It does: https://github.com/gentoo/gentoo-rust/commit/22c29ecd7f0ee5dcf34f443b4febd6e5b318900e

**Comment by perfect7gentleman** [comment]
okay, anyway it doesn't matter for new.
you need to remove dev-util/cargo and add it to package.provide

**Comment by stefantalpalaru** [comment]
> you need to remove dev-util/cargo and add it to package.provide

I tried and it doesn't work. I had to mask
```
=dev-lang/rust-1.22.1
=virtual/rust-1.22.1
```

**Comment by perfect7gentleman** [comment]
did you define version of provided package?
```
 ~ $ cat /etc/portage/profile/package.provided 
sys-fs/e2fsprogs-1.43.7 
sys-libs/e2fsprogs-libs-1.43.7 
media-libs/gst-plugins-base-0.10.36-r2
media-libs/gstreamer-0.10.36-r2
```

**Comment by stefantalpalaru** [comment]
> did you define version of provided package?

Yes, of course. Portage didn't fell for it and still tried to install cargo.

**Comment by o01eg** [comment]
That's why I deletes `cargo` in installation of 9999 version until `virtual/cargo`will be introduced.

**Comment by perfect7gentleman** [comment]
@o01eg, what virtual/cargo is needed for?

**Comment by o01eg** [comment]
To have support for any of `dev-util/cargo`, `dev-util/cargo-bin` or `dev-lang/rust[tools]`.

**Comment by perfect7gentleman** [comment]
honestly, i don't see the point of having only cargo without rust.
dev-lang/rust[tools] means extended = true which means that cargo is installed too.

**Comment by mpkh** [comment]
@perfect7gentleman after your changes rust package is installing cargo either, that's why I've added block for it there, else way there will be conflict

another tricky temporary possible solution you can have is to make some local ebuild/special version of cargo which will just compile nothing and install nothing (but I maybe package.provided can resolve this either)

**Comment by perfect7gentleman** [comment]
@mpkh, i don't know why putting cargo at package.provided doesn't work for @stefantalpalaru.
I have sys-fs/e2fsprogs-1.43.7 & sys-libs/e2fsprogs-libs-1.43.7 there, and everything works fine.

**Comment by mpkh** [comment]
@perfect7gentleman I think it will be reasonable to add cargo to package.provide inside this overlay for now so new users will not face that issue

**Comment by illiasechin** [comment]
Guys, I created new bug:

https://bugs.gentoo.org/640244

Please add your emails there into CC if it's important for you.
