### ISSUE TITLE
[dev-lang/rust-1.22.1] USE="doc" fails

### ISSUE THREAD

**Issue by jreut** [gentoo/gentoo-rust#311]
Installation fails for this ebuild after compilation finishes. I am very new to Gentoo and Portage, but I think there's a little discrepancy between the [configuration](https://github.com/gentoo/gentoo-rust/blob/ed8eccf9fa392997f438094577532168824b9976/dev-lang/rust/rust-1.22.1.ebuild#L110) and [expectation](https://github.com/gentoo/gentoo-rust/blob/ed8eccf9fa392997f438094577532168824b9976/dev-lang/rust/rust-1.22.1.ebuild#L148) of the documentation directory. It seems like the configuration step says the docdir will be something like `<build_dir>/usr/share/doc/rust-1.22.1`, whereas the `mv` command expects it to be at `<build_dir>/usr/share/doc/rust`.

Do we instead want to say something like this?

```ebuild
if use doc ; then
  dodoc -r "${D}/usr/share/doc/${P}"
fi
```

If you'd like to look at them, here is my [build log](https://bpaste.net/show/02700c0b1f4a) (apologies for the ANSI escapes) and my slightly trimmed [environment](https://bpaste.net/show/7f5b430da8b3).

Emerging with `USE='-doc'` is successful.

Thanks!

**Comment by mpkh** [comment]
@jreut we're using rust from gentoo main tree now, please check if issue is still being actual
