### ISSUE TITLE
the main repo added rust-1.23.0 while keeping a separated cargo-0.24.0

### ISSUE THREAD

**Issue by stefantalpalaru** [gentoo/gentoo-rust#320]
This of course breaks compatibility with this overlay. How about adopting the main repo's policy of keeping cargo in its own package?

**Comment by mpkh** [comment]
yes... but ideally we also should keep everything we've got, system llvm (not sure if upstream supports it), virtual packages, -bin packages support, fetch-crates eclass USE flag, not sure if there are other differences

**Comment by mpkh** [comment]
using stack from main tree now, old rust ebuild from this overlay is here: https://github.com/gentoo/gentoo-rust/blob/dd177c2521438d7ddaecf0b48a9ca55ab421ecf3/dev-lang/rust/rust-1.23.0.ebuild
