### ISSUE TITLE
Where can I land patches for the gentoo tree?

### ISSUE THREAD

**Issue by stefson** [gentoo/gentoo-rust#341]
hey there, 

I would like to fix rust-bin and cargo for arm, do you guys know where I can hand in the patches? I mean, the bugzilla has already two bugs for this matter, here doesn't seem to be the best place either, cause you rely on 9999 ebuilds mostly. Are you developing the ebuilds here before they go to the tree? 

thanks for reading

**Comment by mpkh** [comment]
yes and no, we have very random coordination at the moment
I think for gentoo tree you can open PR directly to gentoo/gentoo on github

**Comment by stefson** [comment]
yeah, I noticed this :-) 

Who can I ping for a review on the possible pull request? 
Given that there is a reaction within, lets say, a few days?

**Comment by stefson** [comment]
it is not _that_ difficult: satisfies 13.0 + 17.0 chost for armv6-hf + armv7-hf

```
elif [[ ${CHOST} == armv6*-h* ]]; then
	TRIPLE="arm-unknown-linux-gnueabihf"
elif [[ ${CHOST} == armv7*-h* ]]; then
	TRIPLE="armv7-unknown-linux-gnueabihf"
```

**Comment by mpkh** [comment]
@stefson you can ping anyone on that list https://wiki.gentoo.org/wiki/Project:Rust but aslo @gentoo/rust team on github (should be same), you can also use this overlay if you want some people to test it first, sometimes it's easier to merge something tested by users in addition to some busy maintainer

**Comment by djc** [comment]
I think I've done most of the maintenance on `dev-lang/rust{,-bin}` and `dev-util/cargo`, feel free to ping me directly.

**Comment by stefson** [comment]
Ok, great! 

Is it acceptable for you to go for hardfloat only at the moment? It should be possible to mask rust{-bin} and cargo on softfloat, if you're worried they may end up installing the wrong toolchain.
