### ISSUE TITLE
dev-lang/rust-bin with extended use flag?

### ISSUE THREAD

**Issue by stefson** [gentoo/gentoo-rust#355]
The stages do have a cargo binary in them, would it be possible to use those instead of having to compile cargo? It would be a great timesaver for arm :-)

**Comment by o01eg** [comment]
Why not use `dev-util/cargo-bin` ?

**Comment by stefson** [comment]
Actually because it isn't in tree - hadn't noticed it in this overlay here. But also, it seems as if these ebuilds are for dev versions only, while I don't really care for those. Best thing about USE=extended is that cargo and rust are in sync - it can be a bit of a nasty thing to sort out these problems. 

In the meantime I have implemented a extended useflag, and it works great.

**Comment by o01eg** [comment]
I use dev cargo with stable and dev rustc both and I've not seen issues with it.

**Comment by stefson** [comment]
rust-bin-1.27.1 from tree introduced a cargo use flag, doing exactly what is the most sensible in this case.
