### ISSUE TITLE
dev-lang/rust contans wrong call to x.py

### ISSUE THREAD

**Issue by EinstokFair** [gentoo/gentoo-rust#367]
In the line https://github.com/gentoo/gentoo-rust/blob/master/dev-lang/rust/rust-9999.ebuild#L208
there should be [code]./x.py[/code] instead of just [code]x.py[/code]

Right now it give error during the ebuild install:

    git checkout --quiet d0fc1788123de9844c8088b977cd142021cea1f2
    GIT NEW branch -->
       repository:               https://github.com/rust-lang-nursery/clang/
       at the commit:            d0fc1788123de9844c8088b977cd142021cea1f2
    >>> Source unpacked in /var/tmp/portage/dev-lang/rust-9999/work
    >>> Preparing source in /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src ...
    >>> Source prepared.
    >>> Configuring source in /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src ...
    >>> Source configured.
    >>> Compiling source in /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src ...
    env: ‘x.py’: No such file or directory
     * ERROR: dev-lang/rust-9999::rust failed (compile phase):
     *   (no error message)
     * 
     * Call stack:
     *     ebuild.sh, line 124:  Called src_compile
     *   environment, line 3026:  Called die
     * The specific snippet of code:
     *       env $(cat "${S}"/config.env) ${EPYTHON} x.py build ...

**Comment by o01eg** [comment]
Looks like you have an empty `EPYTHON` variable.
What you get when you call:
```bash
eselect python list
eselect python
eselect python show --python2
eselect python show --python3
```

**Comment by EinstokFair** [comment]
> Looks like you have an empty EPYTHON variable.

yes, I added `einfo "EPYTHON=${EPYTHON}"` into src_compile(), and it says
<a href="https://www.linux.org.ru/forum/general/14457389?cid=14460018">* EPYTHON=</a>

> eselect python list

    Available Python interpreters, in order of preference:
      [1]   python2.7
      [2]   python3.5

> eselect python

it shows usage information

# eselect python show

python2.7

> eselect python show --python2

python2.7

> eselect python show --python3

python3.5

**Comment by o01eg** [comment]
Could you try to launch 
```bash
ECLASS_DEBUG_OUTPUT='on' ebuild rust-9999.ebuild configure
```
?
