### ISSUE TITLE
layman: Overlay "rust" does not exist.

### ISSUE THREAD

**Issue by Nexion** [gentoo/gentoo-rust#379]
Layman currently doesn't have any information about rust overlay, https://api.gentoo.org/overlays/repositories.xml list doesn't mention it. I can only add it manually.

**Comment by cnd** [comment]
@Nexion you can pull request to https://github.com/gentoo/api-gentoo-org/blob/master/files/overlays/repositories.xml or I will do it after Tuesday

**Comment by gentoo90** [comment]
It was there but got removed because of some unresolved issues
https://github.com/gentoo/api-gentoo-org/commit/84ea5ba335fc0bf9bace55c0f292e5cef3902dfb#diff-ac69b5eca2670deff72fc7ee4affa267

**Comment by cnd** [comment]
https://github.com/gentoo/api-gentoo-org/pull/171

**Comment by cnd** [comment]
fixed
