### ISSUE TITLE
dev-util/cargo-0.30.0-r666 builds from 0.29 sources

### ISSUE THREAD

**Issue by okias** [gentoo/gentoo-rust#381]

**Comment by okias** [comment]
after install cargo -V returns 0.29

**Comment by cnd** [comment]
now 0.31.1 build 0.30 version :) I don't understand it https://github.com/gentoo/gentoo-rust/commit/a9d61db860bf053a27794a9b985136180f76a7d5

**Comment by gentoo90** [comment]
What does `cargo -V --verbose` show?

**Comment by cnd** [comment]
@gentoo90 
```
cargo 1.30.0
release: 1.30.0
```

it seems like that it just installs bootstrap which is weird!

**Comment by cnd** [comment]
outdated
