### ISSUE TITLE
dev-lang/rust should depend on the correct version of openssl/libressl

### ISSUE THREAD

**Issue by temporary-username-largedicks** [gentoo/gentoo-rust#401]
Right now the ebuild accepts any version of openssl and libressl, in reality it fails to build with versions outside of a given range which breaks openssl and libressl updates on systems: In particular it should be:

		!libressl? ( <=dev-libs/openssl-1.1.1:= >=dev-libs/openssl-1.0.1:= )
		libressl? ( <=dev-libs/libressl-2.9.0:= >=dev-libs/libressl-2.5:= )

for 1.35.0-r666

**Comment by cnd** [comment]
thanks but you also can PR that change
