### ISSUE TITLE
virtual/cargo::gentoo is going away

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/gentoo-rust#446]
https://bugs.gentoo.org/695698

seems it will not affect you guys as you carry virtual, just heads up. probably will be better if you remove it as well.

going to send removal and eclass change to gentoo-dev for review within next couple of days.

**Comment by gyakovlev** [comment]
https://archives.gentoo.org/gentoo-dev/message/8ac8ba7030fd792aace427e64542863b
https://github.com/gentoo/gentoo/pull/13440

**Comment by gyakovlev** [comment]
ok I wanted to mask it, but realized it can affect overlay users.
all consumers are now switched to virtual/rust in ::gentoo repo.
lmk when I can mask it.

**Comment by gyakovlev** [comment]
switched
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=a9396c31d51a4752a2bdc54fa73019825d2bdcc6

**Comment by gyakovlev** [comment]
It's masked in gentoo. removing completely in a week or two.

**Comment by cnd** [comment]
removed here
