### ISSUE TITLE
rust-999 and rust-9999 download tar.gz stage0 instead of tar.xz

### ISSUE THREAD

**Issue by stefson** [gentoo/gentoo-rust#454]
I'm not really sure how this works? Is it something the ebuild does decide, or is it caused by upstream?

**Comment by stefson** [comment]
upstream issue: https://github.com/rust-lang/rust/issues/65757

**Comment by stefson** [comment]
need to check in bootstrap folder for tar.gz

**Comment by guanqun** [comment]
I haven't used gentoo for a long time, but if gentoo can switch to python3 to build rust, then my PR on the upstream would help in this case. :)
