### ISSUE TITLE
Build is absurdly slow

### ISSUE THREAD

**Issue by alexameen** [gentoo/gentoo-rust#506]
When installing the latest Gentoo release with the amd64 desktop profile building this single package took longer than all 192 other `@world` packages combined.

I'll admit that this intel i3 ain't top of the line, but this single package has been plugging away for 6 hours.

Edit: it finally finished, installing the basic 64 Gentoo desktop profile spent 6.5/7.5 hours building rust.

**Comment by stefson** [comment]
that's normal build time on a dual core I'd say. I have faster Ryzen six core and it takes 45 minutes to build rust-1.47.0 with USE="+system-llvm", hence saving time without llvm bootstraping, and no multilib, so only abi_x86_64

just use rust-bin, it's perfectly fine
